version: "3"
services:

  myng:
    build: ~/Documents/Conf/dockerfile/dockerfile/ubuntu_nginx
    restart: always
    ports: 
      - "80:80"
      - "22:22"
    links:
      - db

  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ~/Documents/Conf/dockerfile/Volumns/mysql/database:/var/lib/mysql