version: "2"
services:
  db:
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ~/Documents/Conf/dockerfile/volumes/mysql/database:/var/lib/mysql